FROM ubuntu:16.04

ENV PYTHON_VERSION=3.7
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PATH /opt/anaconda3/bin:$PATH
ARG MLCOMMONS_INFERENCE_REF=v5.1

WORKDIR /root
ENV HOME /root

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
      git \
      build-essential \
      software-properties-common \
      ca-certificates \
      wget \
      curl \
      htop \
      zip \
      unzip

RUN cd /opt && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh -O miniconda.sh && \
    /bin/bash ./miniconda.sh -b -p /opt/anaconda3 && \
    rm miniconda.sh && \
    /opt/anaconda3/bin/conda clean -tipsy && \
    ln -s /opt/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    conda config --set always_yes yes --set changeps1 no

RUN pip install --upgrade pip==23.3.2
RUN pip install cmake==3.27.9
RUN pip install future==1.0.0 numpy==1.21.6 pillow==9.5.0 opencv-python-headless==4.8.1.78
RUN pip install tflite-runtime==2.14.0
RUN pip install Cython==0.29.37
RUN pip install protobuf==3.20.0
RUN cd /tmp && \
    git clone --recursive --branch "${MLCOMMONS_INFERENCE_REF}" --depth 1 https://github.com/mlcommons/inference && \
    cd inference/loadgen && \
    pip install pybind11==2.10.4 && \
    CFLAGS="-std=c++14" python setup.py install && \
    rm -rf mlperf

ENTRYPOINT ["/bin/bash"]
