apiVersion: batch/v1
kind: Job
metadata:
  name: mlperf-infer-job
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeName: k8s-master01
      containers:
      - name: mlperf-infer
        image: mengxue12/mlperf-infer-imgclassify-cpu:v5.1-litert-multiarch-script
        imagePullPolicy: Always
        # Redirect stdout and stderr to /output/infer.log
        env:
        - name: MODEL_DIR
          value: /data/models/
        - name: DATA_DIR
          value: /data/imagenet/val_1000/
        - name: SCENARIO
          value: "SingleStream"
        - name: NUM_RUN
          value: "1"
        - name: WAIT_BEFORE_SECONDS
          value: "10"
          # adaptation parameters
        - name: MODEL_BASE
          value: "mobilenetv2" # "mobilenetv2,resnetv1"
        - name: QUANTIZATION_TYPE
          value: "tflite"
        - name: RESOLUTION
          value: "224"
        - name: INFERENCE_THREADS
          value: "1"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_ARCH
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeSelector['kubernetes.io/arch']
        - name: BATCHSIZE
          value: "1" # will be used in other scenarios
        
        command: ["/bin/sh", "-c"]
        args:
        - |
          /mlperf/run_lite_infer_sweep.sh \
            --backend tflite \
            --model_base $MODEL_BASE \
            --device cpu \
            --scenario $SCENARIO \
            --resolution $RESOLUTION \
            --inference_threads $INFERENCE_THREADS \
            --max-batchsize $BATCHSIZE \
            --cache 1 \
            --num_run $NUM_RUN \
            --output-base-dir /output \
            --time 10
   
        volumeMounts:
        - name: data-dir
          mountPath: /data/imagenet/
          readOnly: false
        - name: model-dir
          mountPath: /data/models/
          readOnly: true
        - name: inference-results
          mountPath: /output
        - name: host-proc
          mountPath: /host_proc
      restartPolicy: Never
      volumes:
      - name: data-dir
        hostPath:
          path: /mnt/inference/imagenet/
          type: Directory
      - name: model-dir
        hostPath:
          path: /mnt/inference/models/
          type: Directory
      - name: inference-results
        persistentVolumeClaim:
          claimName: inference-results-pvc
      - name: host-proc
        hostPath:
          path: /proc
